# LAB 1: Variables, arrays and scripts

By Lexxi Reddington ~ April 8, 2019

### 1. Read Chapter 1 and 2 from the Student's Guide and complete all the "Your Turns" in Chapter 2.

a) Your Turn 2A

In [5]:
import numpy as np
a = np.zeros(4)
print(a)

a = np.zeros((3,5))
print(a)

a = np.ones(4)
print(a)

a = np.ones((3,5))
print(a)

a = np.eye(3)
print(a)

[0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


b) Your Turn 2B

In [7]:
a = np.array([[2, 3, 5],[7, 11, 13]])
print(a)

[[ 2  3  5]
 [ 7 11 13]]


The result is a two-dimensional array with the first row specified by the 3 numbers in the first set of brackets and the second row specified by the 3 numbers in the second set of brackets

c) Your Turn 2C

In [8]:
a = np.arange(0, 10, 2)
print(a)
b = np.linspace(0, 10, 6)
print(b)

[0 2 4 6 8]
[ 0.  2.  4.  6.  8. 10.]


The result of a is an array starting at 0 and going to 10 (non-inclusive) in increments of 2
The result of b is an array starting at 0 and going to 10 with 6 points total, so 10 is included here

In [11]:
a = np.arange(0, 12, 2)
print(a)
b = np.linspace(0, 10, 6)
print(b)

[ 0  2  4  6  8 10]
[ 0.  2.  4.  6.  8. 10.]


Now the two arrays are the same, as desired

In [12]:
a = np.arange(0, 10, 1.5)
print(a)
b = np.linspace(0, 10, 7)
print(b)

[0.  1.5 3.  4.5 6.  7.5 9. ]
[ 0.          1.66666667  3.33333333  5.          6.66666667  8.33333333
 10.        ]


a and b differ because the method arange is creating an array specified by a start point, an endpoint, and a step, so we get 0 through 10 in steps of 1.5. 10 is not included here because when we add 9 + 1.5 it is more than 10. Conversely, the method linspace is creating an array specified by a start point, an endpoint, and the number of points total. In this case, we get 7 points, including 0 and 10, all equally spaced. The difference between how these 2 methods operate is reflected in a and b. If you want to evaluate a function over the range 0 to 10, the method you would want to use depends on how you want to evaluate the function. Both methods provide an array of equally spaced points, but depending on how the methods are used, we get different results. 

d) Your Turn 2D

In [18]:
a = np.arange(20)
print(a)
print(a[:])
print(a[::])
print(a[5:15])
print(a[5:15:3])
print(a[5::])
print(a[:5:])
print(a[::5])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 5  6  7  8  9 10 11 12 13 14]
[ 5  8 11 14]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 1 2 3 4]
[ 0  5 10 15]


Line 1 creates an array from 0 to 19 in increments of 1
Line 2 prints this array
Line 3 slices then prints the array such that all values in the array are shown
Line 4 slices then prints the array such that, again, all values in the array are shown
Line 5 slices then prints the array such that the start is 5, the end is 15, and the stride is omitted, so by default it is 1. We get 5 to 14 in steps of 1
Line 6 slices then prints the array such that the start is 5, the end is 15, and the stride is 3, so we get 5 to 14 in steps of 3
Line 7 slices then prints the array such that the start is 5, the end is omitted, so by default it is the end of the array, and the stride is omitted so by default it is 1. We therefore get an array starting at 5, ending at 19, with increments of 1
Line 8 slices then prints the array such that the start is omitted, so it is the start of the array by default, the end is 5, and the stride is omitted so it is 1 by default. We get an array from 0 to 4 in steps of 1
Line 9 slices then prints the array such that the start is omitted, so it is the start of the array by default, the end is omitted, so it is the end of the array by default, and the stride is 5. We get an array starting at 0, ending at 15, in steps of 5

e) Your Turn 2E

In [21]:
s = 'Hello, world!'
t = 'I am Python.'
s+' '+t

'Hello world! I am Python.'

When we just type s + t we get 'Hello, world!I am Python.' What we want is a space between '!' and 'I'. To do this, we need to add a space between the end of s and the start of t. The expression: s+' '+t does the trick. All we are doing is concatenating the space onto s, before t, so that the final String that is printed is formatted correctly.

### 2. Write a single script that calculates the following expressions (check your answers with a regular calculator!): 

$a=\frac{2+e^{2.8}}{\sqrt{13}-2}$

In [71]:
a = (2 + math.exp(2.8)) / (math.sqrt(13) - 2)
print(a)

11.488045914800647


$b=\frac{1-(1+\text{ln}2)^{-3.5}}{1+\sqrt{5}}$

In [73]:
b = (1 - (1 + math.log(2, math.e))**-3.5) / (1 + math.sqrt(5))
print(b)

0.26008973689431575


$c=\text{sin}\left(\frac{2-\sqrt{2}}{2+\sqrt{2}}\right)$

In [74]:
x = (2 - math.sqrt(2)) / (2 + math.sqrt(2))
c = math.sin(x)
print(c)

0.17073234104506005


### 3. Given a, b, and c as inputs, write a script that gives the numerical values of the two solutions (real and complex) of the general quadratic equation: 

$ax^2+bx+c=0$

#### a) See what happens if $a=1, b=2, c=3$ to make sure you have included complex solutions.

In [53]:
import cmath
import math

a = 1
b = 2
c = 3

#Calculate the discriminant
d = (b**2) - (4*a*c)

#Find the two solutions
solution1 = (-b-cmath.sqrt(d))/(2*a)
solution2 = (-b+cmath.sqrt(d))/(2*a)

#Print the solutions to the quadratic equation
print("The solutions are {0} and {1}".format(solution1,solution2))

The solutions are (-1-1.4142135623730951j) and (-1+1.4142135623730951j)


#### b) Make your script check the solutions, and print out the solutions including the results of your check.

In [52]:
#Check that the solutions are correct
check1 = (a*(solution1**2)) + (b*solution1) + c
print("When the first solution is plugged back into the equation, the result is",round(check1.real, 4) + round(check1.imag, 4) * 1j,"as expected") #Should be 0

check2 = (a*(solution2**2)) + (b*solution2) + c
print("When the second solution is plugged back into the equation, the result is",round(check2.real, 4) + round(check2.imag, 4) * 1j,"as expected") #Should be 0

When the first solution is plugged back into the equation, the result is 0j as expected
When the second solution is plugged back into the equation, the result is 0j as expected


### 4. Create the following arrays:

#### a) an array of 100 elements all equal to $e$, the base of the natural logarithm

In [89]:
arr = []
for i in range(100):
    arr.append(math.e)
print(arr)
print("The length of this array is",len(arr))

[2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828

#### b) an array in 1-degree increments of all the angles in degrees from 0 to 360 degrees inclusive

In [60]:
arr_deg = []
for i in range(361):
    arr_deg.append(i)
print(arr_deg)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

#### c) an array in 1-degree increments of all the angles in radians from 0 to 360 degrees inclusive. Verify your answers by generating a third array of zeros when you perform the appropriate operations between the arrays you created in b) and c)

In [64]:
arr_rad = []
for i in range(361):
    arr_rad.append(i*(math.pi/180))
print(arr_rad)

compare = []
for i in range(len(arr_deg)):
    value = round(arr_deg[i] - (arr_rad[i]*(180/math.pi)), 2)
    compare.append(value)
print()
print(compare)

[0.0, 0.017453292519943295, 0.03490658503988659, 0.05235987755982989, 0.06981317007977318, 0.08726646259971647, 0.10471975511965978, 0.12217304763960307, 0.13962634015954636, 0.15707963267948966, 0.17453292519943295, 0.19198621771937624, 0.20943951023931956, 0.22689280275926285, 0.24434609527920614, 0.2617993877991494, 0.2792526803190927, 0.29670597283903605, 0.3141592653589793, 0.33161255787892263, 0.3490658503988659, 0.3665191429188092, 0.3839724354387525, 0.4014257279586958, 0.4188790204786391, 0.4363323129985824, 0.4537856055185257, 0.47123889803846897, 0.4886921905584123, 0.5061454830783556, 0.5235987755982988, 0.5410520681182421, 0.5585053606381855, 0.5759586531581288, 0.5934119456780721, 0.6108652381980153, 0.6283185307179586, 0.6457718232379019, 0.6632251157578453, 0.6806784082777885, 0.6981317007977318, 0.7155849933176751, 0.7330382858376184, 0.7504915783575618, 0.767944870877505, 0.7853981633974483, 0.8028514559173916, 0.8203047484373349, 0.8377580409572782, 0.855211333477221

#### d) an array from 12 to 17, not including 17, in 0.2 increments

In [87]:
import numpy as np
arr = []
for i in np.arange(12, 17, 0.2):
    arr.append(round(i,2))
print(arr)

[12.0, 12.2, 12.4, 12.6, 12.8, 13.0, 13.2, 13.4, 13.6, 13.8, 14.0, 14.2, 14.4, 14.6, 14.8, 15.0, 15.2, 15.4, 15.6, 15.8, 16.0, 16.2, 16.4, 16.6, 16.8]


#### e) an array from 12 to 17, including 17, in 0.2 increments

In [88]:
arr = []
for i in np.arange(12, 17.2, 0.2):
    arr.append(round(i,2))
print(arr)

[12.0, 12.2, 12.4, 12.6, 12.8, 13.0, 13.2, 13.4, 13.6, 13.8, 14.0, 14.2, 14.4, 14.6, 14.8, 15.0, 15.2, 15.4, 15.6, 15.8, 16.0, 16.2, 16.4, 16.6, 16.8, 17.0]


### 5. The position of a ball at time $t$ dropped from rest, from a height $h_0$ is given by $y=h_0-\frac{1}{2}gt^2$. Suppose $h_0 =10 m$. 

#### a) Find and print out the sequence of times when the ball passes each half meter assuming the ball is dropped at $t=0$.

In [92]:
arr_y = []
arr_t = []

for i in np.arange(10, -0.5, -0.5):
    arr_y.append(i)

h = 10
g = 9.8

for i in np.arange(10, -0.5, -0.5):
    y = i
    t = math.sqrt((2*(h-y)) / g)
    arr_t.append(t)

print(arr_t)

[0.0, 0.3194382824999699, 0.4517539514526256, 0.5532833351724881, 0.6388765649999398, 0.7142857142857143, 0.7824607964359516, 0.8451542547285166, 0.9035079029052512, 0.9583148474999098, 1.0101525445522108, 1.0594569267279519, 1.1065666703449761, 1.1517511068997928, 1.1952286093343936, 1.2371791482634837, 1.2777531299998797, 1.3170777796132696, 1.3552618543578767, 1.3923991921155663, 1.4285714285714286]


#### b) Once you have created the arrays for $y$ and $t$, type list(zip(y,t)) at the IPython prompt. Explain the result.

The result of this command is that it merges the two arrays, y and t, together by creating pairs. The first element in the y array is paired with the first element in the t array, and so on, so that the reselt is an array of ordered pairs. This lets us see what t-values correspond to which y-values and vice versa.